name: docker-build

on:
  push:
    branches:
      - 'master'
      - 'main'
  repository_dispatch:
    types: [ build ]

jobs:
  docker:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4', '8.0', '8.1']

    steps:
      - name: Checkout patch files
        uses: actions/checkout@v2
      - name: Checkout base dockerfiles
        uses: actions/checkout@v2
        with:
          path: php
          repository: docker-library/php
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Patch dockerfiles
        run: |
          patch -N -p1 -d php < debug.patch
          patch -N -p1 -d php < version.patch
          cd php; ./apply-templates.sh
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: php/${{ matrix.php-versions }}/bullseye/fpm
          push: true
          tags: icewind1991/php-dbg:${{ matrix.php-versions }}-fpm